Support debridge
dex-guru/meta-aggregation-api pull request #23
Opened 2023-04-25 20:29 UTC by mncdg

Created new abstraction ChainSwapInfo that have 2 realization: SingleChainSwapInfo, CrossChainSwapInfo
Created new service DebridgeDlnProviderV1 that does requests:
- {TRADING_API}/v1.0/dln/order/create-order - for creating data for swap
- {TRADING_API}/v1.0/dln/order/quote - for estimation swap 
- {ORDER_API}/api/Orders/filteredList - finding orders
- {TRADING_API}/v1.0/dln/order/{orderId} - get order by id

New provider: debridge

Envs:
 - DEBRIDGE_TRADING_API
 - DEBRIDGE_ORDER_API

2023-04-28 11:13 UTC, shestakoven requested changes
Thanks for your PR, it's pretty good!

But there are few points:
- Let's move crosschain swaps to separate url path (for example /v1/crosschain) and add here `chain_id_to` and `chain_id_from` query params;

- After that I'm not sure that you need `ChainSwapInfo` anymore;

Anything else LGTM!

2023-06-01 10:09 UTC, shestakoven requested changes
This thing with allowance check looks critical. Correct me if I'm wrong. Anything else LGTM.

2023-06-19 09:18 UTC, shestakoven approved these changes
Looks to be working!

2023-06-19 09:18 UTC, shestakoven commented on meta_aggregation_api/providers/debridge_dln_v1/debridge_dln_provider_v1.py
> +            "affiliateFeeRecipient": taker_address,
`'affiliateFeeRecipient': fee_recipient `

2023-07-26 18:47 UTC, evahteev approved these changes
LGTM

2023-07-26 18:47 UTC, merged